Fix python 3.13.11 tests. The xml import is changed and following error is thrown:
AttributeError: 'DocumentFragment' object has no attribute '_id_cache'